[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_audit_examples = "HFi8ekN1E6Pyt2kTbnX55JhPoDCbvBcaM9GmKT4AaPAv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/urataps/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
